_wandb:
    value:
        cli_version: 0.22.3
        e:
            ozxauyic7hnhp278sglxjy3p67qrfvmc:
                codePath: train_scratch_model.py
                codePathLocal: train_scratch_model.py
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "32162967552"
                        used: "5176250368"
                email: homologylee@gmail.com
                executable: /home/ee4483_02/.conda/envs/ee4483/bin/python
                git:
                    commit: e4f57b8f434d0f0e9088d2a8b2fde6afea274c8b
                    remote: https://github.com/codebyhyuk/NTU-IE4483.git
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-e2d696cc-2308-1804-73d2-fe4c02f8023e
                host: gpu-a5000-5.cluster02.eee.ntu.edu.sg
                memory:
                    total: "118158368768"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.39
                program: /home/ee4483_02/NTU-IE4483/train_scratch_model.py
                python: CPython 3.12.12
                root: /home/ee4483_02/NTU-IE4483
                slurm:
                    cluster_name: (null)
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0F00
                    cpu_bind_list: "0x0F00"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    distribution: cyclic
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: ug-course
                    job_cpus_per_node: "4"
                    job_end_time: "1762742986"
                    job_gid: "295800356"
                    job_gpus: "2"
                    job_id: "12580"
                    job_name: resnet_train
                    job_nodelist: gpu-a5000-5
                    job_num_nodes: "1"
                    job_partition: cluster02
                    job_qos: ug-course
                    job_start_time: "1762699786"
                    job_uid: "295800356"
                    job_user: ee4483_02
                    jobid: "12580"
                    launch_node_ipaddr: 11.11.11.170
                    localid: "0"
                    mem_per_node: "24576"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu-a5000-5
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    srun_comm_host: 11.11.11.170
                    srun_comm_port: "43965"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "43965"
                    step_nodelist: gpu-a5000-5
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/ee4483_02/NTU-IE4483
                    submit_host: login-3.cluster02.eee.ntu.edu.sg
                    task_pid: "58112"
                    tasks_per_node: "1"
                    topology_addr: gpu-a5000-5
                    topology_addr_pattern: node
                    umask: "0002"
                startedAt: "2025-11-09T14:50:14.706877Z"
                writerId: ozxauyic7hnhp278sglxjy3p67qrfvmc
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.12.12
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 32
dataset:
    value: dogcat
epochs:
    value: 50
learning_rate:
    value: 0.0001
pretrained:
    value: false
runtime:
    value: "1109225014"
